from django.urls import path
from . import views
from .views import (
    MenuCategoryListCreateView,
    MenuCategoryDetailView,
    MenuItemReviewCreateView,
    TableDetailAPIView,
    AvailableTablesAPIView,
    ContactFormSubmissionView,
    MenuItemIngredientsView,
    FeaturedMenuItemsView,
    DailySpecialListView,
    UserReviewCreateAPIView, 
    MenuItemReviewsListAPIView,
    MenuCategoryListView,
    CreateReviewAPIView,
    UpdateMenuItemAvailabilityAPIView,
    MenuItemSearchView,
    OpeningHoursListView,
    RestaurantDetailAPIView,
    MenuItemDetailAPIView,
    RestaurantOpeningHoursView,
    MenuItemListView,
    MenuItemAvailabilityView,
    MenuItemPriceRangeView,
    MenuItemAvailabilityListView,
    FAQListView,
    AvailableMenuItemCountView,
    ReviewListView,
    OrderSummaryView,
    MenuItemListAPIView,
    AvailableTableListAPIView
)

urlpatterns = [
    # ✅ Menu Category API
    path('api/menu-categories/', MenuCategoryListCreateView.as_view(), name='menu-category-list-create'),
    path('api/menu-categories/<int:pk>/', MenuCategoryDetailView.as_view(), name='menu-category-detail'),
    # Existing routes
    path('api/tables/<int:pk>/', TableDetailAPIView.as_view(), name='table-detail'),
    path('api/tables/available/', AvailableTablesAPIView.as_view(), name='available_tables_api'),
    path('api/contact/', ContactFormSubmissionView.as_view(), name='contact-form-submit'),
    path('api/menu-items/<int:pk>/ingredients/', MenuItemIngredientsView.as_view(), name='menuitem-ingredients'),
    path('api/menu-items/featured/', FeaturedMenuItemsView.as_view(), name='featured-menu-items'),
    path('api/daily-specials/', DailySpecialListView.as_view(), name='daily-specials'),
    path('api/reviews/create/', UserReviewCreateAPIView.as_view(), name='review-create'),
    path('api/menu/<int:menu_item_id>/reviews/', MenuItemReviewsListAPIView.as_view(), name='menuitem-reviews'),
    path('api/menu-categories/', MenuCategoryListView.as_view(), name='menu-categories'),
    path('api/reviews/create/', CreateReviewAPIView.as_view(), name='create-review'),
    path('api/menu-items/<int:pk>/availability/', UpdateMenuItemAvailabilityAPIView.as_view(), name='update-menu-item-availability'),
    path('menu/search/', MenuItemSearchView.as_view(), name='menu-item-search'),
    path('api/opening-hours/', OpeningHoursListView.as_view(), name='opening-hours-list'),
    path('api/restaurant/<int:pk>/', RestaurantDetailAPIView.as_view(), name='restaurant-detail'),
    path('menu/<int:id>/', MenuItemDetailAPIView.as_view(), name='menu-item-detail'),
    path('restaurant/opening-hours/', RestaurantOpeningHoursView.as_view(), name='restaurant-opening-hours'),
    path('menu/items/', MenuItemListView.as_view(), name='menu-items'),
    path('menu-items/<int:pk>/availability/', MenuItemAvailabilityView.as_view(), name='menu-item-availability'),
    path('menu-items/price-range/', MenuItemPriceRangeView.as_view(), name='menuitem-price-range'),
    path('menu-items/availability/', MenuItemAvailabilityListView.as_view(), name='menuitem-availability-list'),
    path('faqs/', FAQListView.as_view(), name='faq-list'),
    path('menu-items/available-count/', AvailableMenuItemCountView.as_view(), name='available-menuitem-count'),
    path('reviews/', views.ReviewListView.as_view(), name='review-list'),
    path('orders/<str:order_id>/summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('menu-items/', MenuItemListAPIView.as_view(), name='menu-item-list'),
    path('api/tables/', AvailableTableListAPIView.as_view(), name='available-tables'),
    path('api/cuisines/', views.CuisineListView.as_view(), name='cuisine-list'),
    path('menu-items/reviews/create/', MenuItemReviewCreateView.as_view(), name="create-menu-item-review"),
]
